#!/bin/bash

if [ -z $1 ]; then
  echo "Run like this: rawz file_to_decompress.rawz" >&2 ; exit 1
else
printf "\x1f\x8b\x08\x00\x00\x00\x00\x00" | cat - $1 | gzip -dc > "$1.log"
echo Your file is: "$1.log"
fi
