#!/bin/bash

## Get the name of the script without its path

progname=${0##*/}

##Default Values

verbose=0
filename=

## List of options the program will accept;
## those options that take arguments are followed by a colon

optstring=f:v

## The loop calls getopts until there are no more options on the command line
## Each option is stored in $opt, any options arguments are stored in OPTARG

while getopts $optstring opt

do
	case $opt in

## $OPTARG contains the arg:ument to the option

		f) filename=$OPTARG ;;
		v) verbose=$(( $verbose + 1 )) ;;
		*) exit 1 ;;
	esac
done

## Remove options from the command line
## $OPTIND points to the next, unparsed argument

shift "$(( $OPTIND - 1 ))"

## Check whether a filename was entered

if [ -n "$filename" ]
then
	if [ $verbose -gt 0 ]
	then
		printf "Filename is %s\n" "$filename"
	fi
else
	if [ $verbose -gt 0 ]
	then
		printf "No Filename entered\n" >&2
	fi
	exit 1
fi

## Check whether file exists

if [ -f "$filename" ]
then
	if [ $verbose -gt 0 ]
	then
		printf "Filename %s found\n" "$filename"
	fi
else
	if [ $verbose -gt 0 ]
	then
		printf "File, %s, done not exist\n" "$filename" >&2
	fi
	exit 2
fi

## If the verbose option is selected,
## print the number of arguments remaining on the command line

if [ $verbose -gt 0 ]
then
	printf "Number of arguments is %d\n" "$#"
fi
