#!/bin/bash

## If $x is set

if [[ ${x+X} = X ]]
then

##if $x is not empty

	if [[ -n $x ]]
	then
		printf "  \$x = %s\n" "$x"
	else
		printf "  \$x is set but empty\n"
	fi
else
	printf " %s is not set\n" "\$x"
fi 
